# Generated by Django 5.0.2 on 2024-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminModel',
            fields=[
                ('name', models.CharField(db_column='admin_name', max_length=20, null=True)),
                ('password', models.CharField(db_column='password', max_length=20, null=True)),
                ('email', models.CharField(db_column='email_id', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('Cate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cate_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='complaintModel',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=40)),
                ('cust_id', models.IntegerField(db_index=True)),
                ('c_status', models.TextField()),
                ('c_desc', models.TextField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustMaterial',
            fields=[
                ('Cate_id', models.IntegerField(db_index=True)),
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cust_martial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='empModel',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_firstname', models.CharField(max_length=20)),
                ('emp_lastlame', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=30)),
                ('emp_contact', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('emp_DOJ', models.DateField()),
                ('emp_salary', models.IntegerField()),
                ('emp_address', models.CharField(max_length=100)),
                ('emp_img', models.CharField(max_length=200)),
                ('emp_role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('mate_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_id', models.IntegerField(db_index=True)),
                ('mat_price', models.IntegerField()),
                ('mat_type', models.CharField(max_length=30)),
                ('mat_img', models.CharField(max_length=200)),
                ('mat_color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mateial_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=20)),
                ('p_id', models.IntegerField()),
                ('offer_type', models.CharField(max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('O_id', models.IntegerField()),
                ('p_id', models.IntegerField()),
                ('p_name', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ordersModel',
            fields=[
                ('O_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Cust_id', models.IntegerField(max_length=10)),
                ('O_date', models.DateField()),
                ('O_address', models.CharField(max_length=100)),
                ('o_total_amt', models.IntegerField(max_length=5)),
                ('o_disc_price', models.IntegerField(max_length=5)),
                ('O_payment_mtd', models.CharField(max_length=30)),
                ('O_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('p_img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_img_link', models.CharField(max_length=200)),
                ('p_id', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'product_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('P_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=30)),
                ('P_desc', models.CharField(max_length=100)),
                ('P_category_id', models.IntegerField(max_length=5)),
                ('P_curstock', models.IntegerField(max_length=10)),
                ('P_price', models.IntegerField(max_length=10)),
                ('P_rating', models.FloatField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_id', models.IntegerField(db_index=True)),
                ('material_id', models.IntegerField(db_index=True)),
                ('mate_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'selected_mat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('Cust_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email_id', models.CharField(max_length=30)),
                ('Contact_no', models.BigIntegerField()),
                ('Dob', models.DateField(null=True)),
                ('Password', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('Profile_pic', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
