# Generated by Django 5.0.1 on 2024-02-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_ordersmodel_productimage_productmodel_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('Cate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cate_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
