# Generated by Django 5.0.1 on 2024-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=40)),
                ('cust_id', models.IntegerField(db_index=True)),
                ('c_status', models.TextField()),
                ('c_desc', models.TextField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMaterial',
            fields=[
                ('Cate_id', models.IntegerField(db_index=True)),
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cust_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('mate_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_id', models.IntegerField(db_index=True)),
                ('mat_price', models.IntegerField()),
                ('mat_type', models.CharField(max_length=30)),
                ('mat_img', models.CharField(max_length=200)),
                ('mat_color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mateial_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_id', models.IntegerField(db_index=True)),
                ('material_id', models.IntegerField(db_index=True)),
                ('mate_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'selected_mat',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
