# Generated by Django 5.0.1 on 2024-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_category_complaint_customermaterial_materialtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintModel',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=40)),
                ('cust_id', models.IntegerField(db_index=True)),
                ('c_status', models.TextField()),
                ('c_desc', models.TextField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='orderProModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_id', models.IntegerField(max_length=10)),
                ('p_id', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'order_product',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
