# Generated by Django 5.0.2 on 2024-02-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_ordersmodel_productmodel_usermodel'),
        ('admin', '0008_orderproduct_delete_orderpromodel'),
    ]

    operations = [
    ]
