# Generated by Django 5.0.1 on 2024-02-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empModel',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_firstname', models.CharField(max_length=20)),
                ('emp_lastlame', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=30)),
                ('emp_contact', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('emp_DOJ', models.DateField()),
                ('emp_salary', models.IntegerField()),
                ('emp_address', models.CharField(max_length=100)),
                ('emp_img', models.CharField(max_length=200)),
                ('emp_role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
