# Generated by Django 5.0.1 on 2024-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminModel',
            fields=[
                ('name', models.CharField(db_column='admin_name', max_length=20, null=True)),
                ('password', models.CharField(db_column='password', max_length=20, null=True)),
                ('email', models.CharField(db_column='email_id', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email_id', models.CharField(max_length=30)),
                ('Contact_no', models.IntegerField()),
                ('Dob', models.DateField(null=True)),
                ('Password', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('Profile_pic', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ordersModel',
            fields=[
                ('O_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Cust_id', models.IntegerField(max_length=10)),
                ('O_date', models.DateField()),
                ('O_address', models.CharField(max_length=100)),
                ('o_total_amt', models.IntegerField(max_length=5)),
                ('o_disc_price', models.IntegerField(max_length=5)),
                ('O_payment_mtd', models.CharField(max_length=30)),
                ('O_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('P_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=30)),
                ('P_desc', models.CharField(max_length=100)),
                ('P_category_id', models.IntegerField(max_length=5)),
                ('P_curstock', models.IntegerField(max_length=10)),
                ('P_price', models.IntegerField(max_length=10)),
                ('P_rating', models.FloatField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
