# Generated by Django 5.0.1 on 2024-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_product_productimagemodel_delete_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.IntegerField(db_column='Cate_id', primary_key=True, serialize=False)),
                ('cate_name', models.CharField(db_column='Cate_name', max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
