# Generated by Django 5.0.2 on 2024-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_cart_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'order_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('O_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Cust_id', models.IntegerField(max_length=10)),
                ('O_date', models.DateField()),
                ('O_address', models.CharField(max_length=100)),
                ('o_total_amt', models.IntegerField(max_length=5)),
                ('o_disc_price', models.IntegerField(max_length=5)),
                ('O_payment_mtd', models.CharField(max_length=30)),
                ('O_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ordersModel',
        ),
    ]
